// Woordenlijst met luchtvaartafkortingen. Na elk antwoord toont de site de afkortingen die in de vraag,
// de antwoorden of de uitleg voorkomen, met de volledige benaming en een korte uitleg.
// Formaat: AFKORTING: [volledige benaming, korte uitleg in het Nederlands]

window.GLOSSARY = (function () {
  'use strict';

  const G = {
    // --- Radionavigatie ---
    VOR: ['VHF Omnidirectional Range', 'grondstation dat in alle richtingen radialen uitzendt; aan boord lees je af op welke radiaal je zit.'],
    DVOR: ['Doppler VOR', 'nauwkeurigere uitvoering van een VOR-baken.'],
    DME: ['Distance Measuring Equipment', 'meet de schuine afstand (in NM) tussen het vliegtuig en het grondstation.'],
    NDB: ['Non-Directional Beacon', 'radiobaken op de grond (LF/MF) dat in alle richtingen hetzelfde signaal uitzendt; je peilt het met een ADF.'],
    ADF: ['Automatic Direction Finder', 'ontvanger aan boord die de richting naar een NDB aanwijst.'],
    RBI: ['Relative Bearing Indicator', 'ADF-instrument met vaste kaart (0 bovenaan = neus); toont de relatieve peiling.'],
    RMI: ['Radio Magnetic Indicator', 'instrument met een kompasroos die meedraait met de koers; de naald wijst rechtstreeks de magnetische richting naar het station.'],
    CDI: ['Course Deviation Indicator', 'naald op de VOR-indicator die toont hoeveel je naast de gekozen koers zit.'],
    OBS: ['Omni Bearing Selector', 'knop op de VOR-indicator waarmee je de gewenste koers (radiaal) instelt.'],
    HSI: ['Horizontal Situation Indicator', 'combineert koersgyro en VOR/ILS-aanwijzing in één instrument.'],
    VDF: ['VHF Direction Finder', 'grondpeiler: het grondstation bepaalt uit je radiobericht in welke richting je zit.'],
    ILS: ['Instrument Landing System', 'precisienaderingssysteem met koers (localizer) en glijpad.'],
    LOC: ['Localizer', 'het koersdeel van het ILS.'],
    SSR: ['Secondary Surveillance Radar', 'secundaire radar die de transponder ondervraagt en zo code en hoogte ontvangt.'],
    GNSS: ['Global Navigation Satellite System', 'satellietnavigatie, bv. GPS of Galileo.'],
    GPS: ['Global Positioning System', 'Amerikaans satellietnavigatiesysteem.'],
    WGS: ['World Geodetic System (WGS-84)', 'referentie-ellipsoïde voor coördinaten in de luchtvaart.'],
    TO: ['TO-vlag (VOR)', 'als je de ingestelde OBS-koers vliegt, kom je naar het station toe.'],
    FROM: ['FROM-vlag (VOR)', 'als je de ingestelde OBS-koers vliegt, vlieg je van het station weg.'],
    VHF: ['Very High Frequency', 'frequentieband 30–300 MHz; o.a. voor spraak (118–137 MHz) en VOR. Bereik ongeveer tot de horizon.'],
    HF: ['High Frequency', 'frequentieband 3–30 MHz; groot bereik via de ionosfeer.'],
    MF: ['Medium Frequency', 'frequentieband 300 kHz–3 MHz; o.a. voor NDB’s.'],
    LF: ['Low Frequency', 'frequentieband 30–300 kHz; o.a. voor NDB’s.'],

    // --- Q-codes en peilingen ---
    QDM: ['Q-code: magnetische koers naar het station', 'de magnetische koers die je (bij windstil) vliegt om bij het station te komen.'],
    QDR: ['Q-code: magnetische peiling vanaf het station', 'de magnetische richting van het station naar jou (= de radiaal).'],
    QTE: ['Q-code: ware peiling vanaf het station', 'zoals QDR, maar ten opzichte van het ware noorden.'],
    QUJ: ['Q-code: ware koers naar het station', 'zoals QDM, maar ten opzichte van het ware noorden.'],
    QNH: ['Q-code: luchtdruk herleid tot zeeniveau', 'met QNH ingesteld toont de hoogtemeter de hoogte boven zeeniveau (altitude).'],
    QFE: ['Q-code: luchtdruk op vliegveldhoogte', 'met QFE ingesteld toont de hoogtemeter de hoogte boven het vliegveld (0 op de grond).'],
    QNE: ['Q-code: standaarddruk 1013,25 hPa', 'met 1013,25 hPa ingesteld toont de hoogtemeter het vliegniveau (drukhoogte).'],
    QFF: ['Q-code: luchtdruk herleid tot zeeniveau (meteo)', 'gebruikt op weerkaarten; houdt rekening met de werkelijke temperatuur.'],

    // --- Koersen, snelheden, hoogtes ---
    TT: ['True Track', 'ware grondkoers: de richting over de grond t.o.v. het ware noorden.'],
    TH: ['True Heading', 'ware luchtkoers: waar de neus naartoe wijst t.o.v. het ware noorden.'],
    MT: ['Magnetic Track', 'magnetische grondkoers.'],
    MH: ['Magnetic Heading', 'magnetische luchtkoers.'],
    MC: ['Magnetic Course / Compass Course', 'in een navigatielog: de kompaskoers (MH gecorrigeerd voor deviatie).'],
    CH: ['Compass Heading', 'kompaskoers: wat het magnetisch kompas aanwijst (MH ± deviatie).'],
    TC: ['True Course', 'ware (geplande) koerslijn.'],
    WCA: ['Wind Correction Angle', 'opstuurhoek: hoeveel je tegen de wind in stuurt om je grondkoers te houden.'],
    VAR: ['Variatie', 'hoek tussen het ware en het magnetische noorden.'],
    DEV: ['Deviatie', 'kompasfout door het magnetisch veld van het vliegtuig zelf.'],
    TAS: ['True Airspeed', 'ware luchtsnelheid: de echte snelheid t.o.v. de lucht.'],
    IAS: ['Indicated Airspeed', 'aangewezen snelheid op de snelheidsmeter.'],
    CAS: ['Calibrated Airspeed', 'IAS gecorrigeerd voor instrument- en positiefouten.'],
    EAS: ['Equivalent Airspeed', 'CAS gecorrigeerd voor samendrukbaarheid (bij hoge snelheden).'],
    GS: ['Ground Speed', 'grondsnelheid: snelheid over de grond (TAS ± wind).'],
    ROD: ['Rate of Descent', 'daalsnelheid, meestal in ft/min.'],
    ROC: ['Rate of Climb', 'stijgsnelheid, meestal in ft/min.'],
    FL: ['Flight Level (vliegniveau)', 'drukhoogte in honderden voet t.o.v. 1013,25 hPa, bv. FL055 = 5500 ft.'],
    AMSL: ['Above Mean Sea Level', 'boven gemiddeld zeeniveau.'],
    MSL: ['Mean Sea Level', 'gemiddeld zeeniveau.'],
    AGL: ['Above Ground Level', 'boven de grond.'],
    MEF: ['Maximum Elevation Figure', 'hoogste terrein/obstakel in een kaartvak plus een marge, op VFR-kaarten.'],
    ETA: ['Estimated Time of Arrival', 'verwachte aankomsttijd.'],
    ETD: ['Estimated Time of Departure', 'verwachte vertrektijd.'],
    EOBT: ['Estimated Off-Block Time', 'verwachte tijd waarop het vliegtuig vertrekt van de parkeerplaats (vluchtplan).'],
    UTC: ['Coordinated Universal Time', 'wereldtijd die in de luchtvaart altijd gebruikt wordt (België: UTC+1 in de winter, UTC+2 in de zomer).'],
    CET: ['Central European Time', 'Midden-Europese tijd = UTC+1.'],
    CEST: ['Central European Summer Time', 'Midden-Europese zomertijd = UTC+2.'],
    MEZT: ['Midden-Europese zomertijd', '= CEST = UTC+2.'],
    LMT: ['Local Mean Time', 'plaatselijke middelbare zonnetijd.'],
    NM: ['Nautical Mile (zeemijl)', '1 NM = 1852 m = 1 boogminuut breedte.'],
    SM: ['Statute Mile (landmijl)', '1 SM = 1609 m.'],
    USG: ['US gallon', '1 USG = 3,785 liter.'],
    RPM: ['Revolutions Per Minute', 'toerental van de motor/propeller.'],
    TPM: ['Toeren per minuut', '= RPM, toerental.'],
    GPH: ['Gallons Per Hour', 'brandstofverbruik in gallon per uur.'],

    // --- Vliegtuig, prestaties, massa ---
    CG: ['Center of Gravity', 'zwaartepunt van het vliegtuig.'],
    MTOM: ['Maximum Take-Off Mass', 'maximale startmassa.'],
    POH: ['Pilot’s Operating Handbook', 'vlieghandboek van het vliegtuigtype.'],
    AFM: ['Aircraft Flight Manual', 'goedgekeurd vlieghandboek van het vliegtuig.'],
    VNE: ['Velocity Never Exceed', 'snelheid die je nooit mag overschrijden (rode lijn).'],
    VNO: ['Maximum structural cruising speed', 'maximale snelheid voor normaal gebruik (einde groene boog).'],
    VFE: ['Maximum Flap Extended speed', 'maximale snelheid met kleppen uit (einde witte boog).'],
    VS0: ['Stall speed in landing configuration', 'overtreksnelheid met kleppen en wielen uit (begin witte boog).'],
    VS1: ['Stall speed in a specified configuration', 'overtreksnelheid in schone configuratie (begin groene boog).'],
    VA: ['Manoeuvring speed', 'manoeuvreersnelheid: boven deze snelheid kan volle roeruitslag de structuur overbelasten.'],
    AVGAS: ['Aviation Gasoline', 'vliegtuigbenzine voor zuigermotoren; 100LL is blauw, ongeveer 0,72 kg/l.'],
    CHT: ['Cylinder Head Temperature', 'cilinderkoptemperatuur.'],
    EGT: ['Exhaust Gas Temperature', 'uitlaatgastemperatuur, gebruikt bij het leunen van het mengsel.'],
    OAT: ['Outside Air Temperature', 'buitenluchttemperatuur.'],
    VSI: ['Vertical Speed Indicator', 'variometer: toont de stijg- of daalsnelheid.'],
    TMG: ['Touring Motor Glider', 'motorzwever.'],
    CFRP: ['Carbon Fibre Reinforced Plastic', 'koolstofvezelversterkte kunststof.'],
    SEP: ['Single Engine Piston', 'eenmotorig vliegtuig met zuigermotor (bevoegdverklaring).'],
    TORA: ['Take-Off Run Available', 'beschikbare startbaanlengte.'],
    LDA: ['Landing Distance Available', 'beschikbare landingsafstand.'],
    RWY: ['Runway', 'start- en landingsbaan.'],
    PARE: ['Power – Ailerons – Rudder – Elevator', 'geheugensteun voor het herstel uit een vrille.'],

    // --- Meteo ---
    ISA: ['International Standard Atmosphere', 'standaardatmosfeer: 15 °C en 1013,25 hPa op zeeniveau, −2 °C per 1000 ft.'],
    METAR: ['Meteorological Aerodrome Report', 'actueel weerbericht van een vliegveld.'],
    TAF: ['Terminal Aerodrome Forecast', 'weersverwachting voor een vliegveld.'],
    SIGMET: ['Significant Meteorological Information', 'waarschuwing voor gevaarlijk weer (onweer, ijs, turbulentie) in een FIR.'],
    AIRMET: ['Airmen’s Meteorological Information', 'waarschuwing voor weer dat vooral laagvliegend verkeer raakt.'],
    GAMET: ['General Aviation Meteorological forecast', 'gebiedsverwachting voor laagvliegend verkeer.'],
    GAFOR: ['General Aviation Forecast', 'routeverwachting voor de kleine luchtvaart (VFR-condities).'],
    VOLMET: ['Meteorological information for aircraft in flight', 'radio-uitzending met METARs/TAFs van meerdere vliegvelden.'],
    ATIS: ['Automatic Terminal Information Service', 'automatische uitzending met weer en baan-informatie van een vliegveld.'],
    PIREP: ['Pilot Report', 'weerwaarneming gemeld door een piloot.'],
    SWC: ['Significant Weather Chart', 'kaart met vlieggevaren (fronten, Cb, turbulentie, ijs).'],
    CAT: ['Clear Air Turbulence', 'turbulentie in heldere lucht, zonder wolken.'],
    HRV: ['High Resolution Visible', 'satellietkanaal met zichtbaar licht in hoge resolutie.'],
    RGB: ['Red-Green-Blue', 'kleurensatellietbeeld uit meerdere gecombineerde kanalen.'],
    IR: ['Infrarood', 'satellietbeeld op basis van temperatuur (koude toppen = hoge wolken).'],
    SCT: ['Scattered', '3–4 achtsten bewolking.'],
    FEW: ['Few', '1–2 achtsten bewolking.'],
    SHRA: ['Showers of Rain', 'regenbuien (METAR-code).'],
    TSRA: ['Thunderstorm with Rain', 'onweer met regen (METAR-code).'],
    BR: ['Brume (mist)', 'nevel/mist met zicht 1000–5000 m (METAR-code).'],
    FG: ['Fog', 'mist met zicht onder 1000 m (METAR-code).'],
    HZ: ['Haze', 'heiigheid door droge deeltjes (METAR-code).'],
    BCFG: ['Banks of Fog', 'mistbanken (METAR-code).'],
    Cb: ['Cumulonimbus', 'onweerswolk.'],
    Cu: ['Cumulus', 'stapelwolk.'],
    Ci: ['Cirrus', 'hoge ijswolk, vezelig.'],
    Ns: ['Nimbostratus', 'dikke, grijze regenwolk.'],

    // --- Luchtverkeer, luchtruim, regelgeving ---
    VFR: ['Visual Flight Rules', 'zichtvliegvoorschriften.'],
    IFR: ['Instrument Flight Rules', 'instrumentvliegvoorschriften.'],
    VMC: ['Visual Meteorological Conditions', 'weersomstandigheden waarin zichtvliegen toegelaten is.'],
    IMC: ['Instrument Meteorological Conditions', 'weersomstandigheden onder de VMC-minima.'],
    SVFR: ['Special VFR', 'bijzondere VFR-vlucht in een controlezone bij weer onder de VMC-minima.'],
    ATC: ['Air Traffic Control', 'luchtverkeersleiding.'],
    ATS: ['Air Traffic Services', 'luchtverkeersdiensten (ATC, FIS, alarmering).'],
    FIS: ['Flight Information Service', 'vluchtinformatiedienst (in België: Brussels Information).'],
    FIR: ['Flight Information Region', 'vluchtinformatiegebied, bv. de Brussels FIR.'],
    UIR: ['Upper Information Region', 'bovenste vluchtinformatiegebied.'],
    AIS: ['Aeronautical Information Service', 'luchtvaartinformatiedienst (AIP, NOTAM).'],
    ARO: ['ATS Reporting Office', 'meldpunt voor vluchtplannen.'],
    AFIL: ['Air-filed flight plan', 'vluchtplan dat tijdens de vlucht via de radio wordt ingediend.'],
    SAR: ['Search and Rescue', 'opsporing en redding.'],
    ALR: ['Alerting service', 'alarmeringsdienst.'],
    TWR: ['Tower', 'plaatselijke verkeersleiding (toren).'],
    APP: ['Approach', 'naderingsverkeersleiding.'],
    ACC: ['Area Control Centre', 'algemene verkeersleiding (en-route).'],
    CTR: ['Control Zone', 'gecontroleerd luchtruim rond een vliegveld, vanaf de grond.'],
    TMA: ['Terminal Control Area', 'gecontroleerd naderingsgebied boven een of meer vliegvelden.'],
    RMZ: ['Radio Mandatory Zone', 'zone waar uitluisteren en radiocontact verplicht is.'],
    TMZ: ['Transponder Mandatory Zone', 'zone waar een werkende transponder (mode A+C of S) verplicht is.'],
    TRA: ['Temporary Reserved Area', 'tijdelijk gereserveerd luchtruim (bv. militair).'],
    AIP: ['Aeronautical Information Publication', 'luchtvaartgids met de vaste luchtvaartinformatie van een land.'],
    GEN: ['AIP – deel General', 'algemeen deel van de AIP.'],
    ENR: ['AIP – deel En-route', 'luchtruim, routes en gebieden.'],
    AD: ['AIP – deel Aerodromes', 'vliegvelden.'],
    AIC: ['Aeronautical Information Circular', 'luchtvaartinformatiecirculaire.'],
    NOTAM: ['Notice to Airmen', 'bericht over tijdelijke wijzigingen (gesloten baan, defect baken, gebieden…).'],
    SERA: ['Standardised European Rules of the Air', 'Europese luchtverkeersregels (Verordening (EU) 923/2012).'],
    EASA: ['European Union Aviation Safety Agency', 'Europees Agentschap voor de veiligheid van de luchtvaart.'],
    ICAO: ['International Civil Aviation Organization', 'internationale burgerluchtvaartorganisatie van de VN.'],
    ECQB: ['European Central Question Bank', 'Europese vragenbank voor de theorie-examens.'],
    BCAA: ['Belgian Civil Aviation Authority', 'Belgische luchtvaartautoriteit (= DGLV).'],
    DGLV: ['Directoraat-generaal Luchtvaart', 'Belgische luchtvaartautoriteit binnen de FOD Mobiliteit.'],
    PPL: ['Private Pilot Licence', 'brevet van privépiloot.'],
    ULM: ['Ultra-Léger Motorisé', 'ultralicht motorluchtvaartuig.'],
    FCL: ['Flight Crew Licensing', 'EASA-regels voor vergunningen (Part-FCL).'],
    MED: ['Medical', 'EASA-regels voor medische keuring (Part-MED).'],
    SFCL: ['Sailplane Flight Crew Licensing', 'EASA-regels voor zweefvliegvergunningen (Part-SFCL).'],
    ARC: ['Airworthiness Review Certificate', 'bewijs van luchtwaardigheidsbeoordeling, jaarlijks te vernieuwen.'],
    CS: ['Certification Specifications', 'EASA-certificatievoorschriften, bv. CS-23 voor kleine vliegtuigen.'],
    ABN: ['Aerodrome Beacon', 'draaiend lichtbaken op een vliegveld.'],
    INCERFA: ['Uncertainty phase', 'onzekerheidsfase (eerste alarmeringsfase).'],
    ALERFA: ['Alert phase', 'alarmeringsfase.'],
    DETRESFA: ['Distress phase', 'noodfase.'],
    MAYDAY: ['Noodsignaal (distress)', 'ernstig en onmiddellijk gevaar, onmiddellijke hulp nodig.'],
    PAN: ['PAN PAN – urgentiesignaal', 'dringende situatie, maar geen onmiddellijk gevaar.'],
    IDENT: ['Identificatie (transponder)', 'knop die je radarblip even laat oplichten bij de verkeersleiding.'],
    H24: ['24 uur per dag', 'continu open of in dienst.'],
    HX: ['Geen vaste openingsuren', 'werkt op onregelmatige tijden.'],
    HJ: ['Van zonsopgang tot zonsondergang', 'openingsuren overdag.'],
    HN: ['Van zonsondergang tot zonsopgang', 'openingsuren ’s nachts.'],
    OBST: ['Obstacle', 'obstakel.']
  };

  // Zoek de afkortingen in een tekst, in volgorde van eerste voorkomen.
  function find(texts) {
    const seen = [];
    const add = key => { if (G[key] && !seen.includes(key)) seen.push(key); };
    for (const t of texts) {
      for (const m of String(t || '').match(/\b[A-Z][A-Za-z0-9]{1,7}\b/g) || []) {
        if (/^FL\d+$/.test(m)) add('FL');
        else if (/^CS\d+$/.test(m)) add('CS');
        else add(m);
      }
    }
    // TO en FROM samen tonen als één van beide voorkomt
    if (seen.includes('TO') && !seen.includes('FROM')) seen.splice(seen.indexOf('TO') + 1, 0, 'FROM');
    if (seen.includes('FROM') && !seen.includes('TO')) seen.splice(seen.indexOf('FROM'), 0, 'TO');
    return seen.map(k => ({ key: k, full: G[k][0], text: G[k][1] }));
  }

  return { find, entries: G };
})();
