"""Merge extracted questions (data/*.json), explanations (content/*.json) and
patches (content/_patches.json) into js/bank.js for the static website.

Usage: python3 tools/build.py
"""
import glob, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ULM theory exam (DGLV) only covers Air Law, Human Performance, Meteorology and
# Communication. Within Air Law, only the generic rules (SERA, airspace, ATS,
# aerodromes, signals, SAR, accidents) apply to ULM; EASA licensing,
# airworthiness and medical topics are PPL-only.
ULM_AIR_LAW_PREFIXES = ("10.5.1", "10.5.3", "10.5.4.1", "10.5.4.2", "10.5.5",
                        "10.6", "10.7", "10.8", "10.9", "10.10", "10.12")
ULM_SUBJECTS = {"human_performance", "communications", "meteorology"}


def licences(subject, topic):
    lic = ["PPL"]
    if subject in ULM_SUBJECTS or (subject == "air_law" and topic.startswith(ULM_AIR_LAW_PREFIXES)):
        lic.append("ULM")
    return lic


def main():
    patches = json.load(open(os.path.join(ROOT, "content", "_patches.json"), encoding="utf-8"))
    replacements = patches.get("_replace", {})

    def fix(text):
        for old, new in replacements.items():
            text = text.replace(old, new)
        return text
    bank, problems = {}, []
    for path in sorted(glob.glob(os.path.join(ROOT, "data", "*.json"))):
        subject = os.path.splitext(os.path.basename(path))[0]
        questions = json.load(open(path, encoding="utf-8"))
        cpath = os.path.join(ROOT, "content", subject + ".json")
        content = json.load(open(cpath, encoding="utf-8")) if os.path.exists(cpath) else {}
        out = []
        for q in questions:
            p = patches.get(q["id"], {})
            options = list(q["options"])
            for i, text in p.get("options", {}).items():
                options[int(i)] = text
            c = content.get(q["id"])
            if not c:
                problems.append(f"{subject}/{q['id']}: geen uitleg")
                c = [""]
            lo = q["topic"].split(" ", 1)
            out.append({
                "id": q["id"],
                "lo": lo[0],
                "loText": lo[1] if len(lo) > 1 else "",
                "q": fix(p.get("question", q["question"])),
                "o": [fix(o) for o in options],
                "c": q["correct"],
                "img": q["images"],
                "e": c[0],
                "src": c[1] if len(c) > 1 else "syl",
                "ref": c[2] if len(c) > 2 else "",
                "review": len(c) > 3 and c[3] == "review",
                "lic": licences(subject, q["topic"]),
            })
        bank[subject] = out
    with open(os.path.join(ROOT, "js", "bank.js"), "w", encoding="utf-8") as fh:
        fh.write("// GENERATED by tools/build.py – do not edit by hand.\n")
        fh.write("window.QUESTION_BANK = ")
        json.dump(bank, fh, ensure_ascii=False, separators=(",", ":"))
        fh.write(";\n")
    total = sum(len(v) for v in bank.values())
    print(f"{total} vragen in {len(bank)} vakken geschreven naar js/bank.js")
    for p in problems:
        print("WAARSCHUWING:", p, file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
